; app0.inc - アプリケーション／タイトル
; 


; ゼロページ
;
APP0_0                              :=  $e0
APP0_0_PROC                         :=  $e0
APP0_0_PROC_L                       :=  $e0
APP0_0_PROC_H                       :=  $e1
APP0_0_STATE                        :=  $e2
APP0_0_BRUN                         :=  $e3
APP0_0_USER                         :=  $e4
APP0_0_USER_END                     :=  $fb
APP0_0_WORK_0                       :=  $fc
APP0_0_WORK_1                       :=  $fd
APP0_0_WORK_2                       :=  $fe
APP0_0_WORK_3                       :=  $ff

