; app1.inc - アプリケーション／ニューゲーム
; 


; ゼロページ
;
APP1_0                              :=  $e0
APP1_0_PROC                         :=  $e0
APP1_0_PROC_L                       :=  $e0
APP1_0_PROC_H                       :=  $e1
APP1_0_STATE                        :=  $e2
APP1_0_BRUN                         :=  $e3
APP1_0_USER                         :=  $e4
APP1_0_USER_END                     :=  $fb
APP1_0_WORK_0                       :=  $fc
APP1_0_WORK_1                       :=  $fd
APP1_0_WORK_2                       :=  $fe
APP1_0_WORK_3                       :=  $ff

