; app2.inc - アプリケーション／ゲーム
; 


; ゼロページ
;
APP2_0                              :=  $e0
APP2_0_PROC                         :=  $e0
APP2_0_PROC_L                       :=  $e0
APP2_0_PROC_H                       :=  $e1
APP2_0_STATE                        :=  $e2
APP2_0_BRUN                         :=  $e3
APP2_0_USER                         :=  $e4
APP2_0_USER_END                     :=  $fb
APP2_0_WORK_0                       :=  $fc
APP2_0_WORK_1                       :=  $fd
APP2_0_WORK_2                       :=  $fe
APP2_0_WORK_3                       :=  $ff

