; game.inc - ゲーム
; 


; ゼロページ
;
GAME_0                                  :=  APP2_0_USER

; WORK
GAME_0_WORK_0                           :=  APP2_0_WORK_0
GAME_0_WORK_1                           :=  APP2_0_WORK_1
GAME_0_WORK_2                           :=  APP2_0_WORK_2
GAME_0_WORK_3                           :=  APP2_0_WORK_3


; ゲーム
;

; エネミーの生成
GAME_SPAWN_SIZE                         =   4
GAME_SPAWN_INTERVAL                     =   11

; 速度
GAME_SPEED_SLOW                         =   0
GAME_SPEED_NORMAL                       =   1
GAME_SPEED_FAST                         =   2
